[[headers]]
  for = "/Build/*.data.br" # .data.br 파일 경로
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/*.wasm.br" # .wasm.br 파일 경로
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]
  for = "/Build/*.js.br" # .js.br 파일 경로
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/*.unityweb.br" # .unityweb.br 파일 경로
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"